global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "jenkins"
    metrics_path: /prometheus
      - targets: ["host.docker.internal:8080"]

  - job_name: "springboot"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8080"]
